version: '3.1'
services:
  mysql-server:
    image:                  mysql
    ports:
     - "3306:3306"
    hostname:               mysql-server
    container_name:         mysql-server
    restart:                unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD:  userpass
      MYSQL_DATABASE: DAM
      #MYSQL_USER: root
      #MYSQL_PASSWORD: userpass
    volumes:
      -                     ./database:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    #tty: true
    networks:
      -                     net-web-app  
  phpmyadmin:
    image:                  phpmyadmin/phpmyadmin:latest
    hostname:               phpmyadmin
    container_name:         phpmyadmin
    restart:                unless-stopped
    environment:
      PMA_HOST:             mysql-server
      PMA_PORT:             3306
      MYSQL_ROOT_PASSWORD:  userpass
    networks:
      -                     net-web-app
    depends_on:
      -                     mysql-server
    ports:
      -                     "8081:80"
  nodeapp:
    image: abassi/nodejs-server:10.0-dev
    hostname: nodeapp
    container_name: nodeapp
    restart: always  
    volumes:
     - ./src:/home/node/app/src
    networks:
     - net-web-app
    depends_on:
     - mysql-server
    ports:
     - "3000:3000"
    command: nodemon src/index.js

# Create network called web with driver bridge
networks:
  net-web-app:
    driver: bridge
